name: Validate IFC Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-ifc:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install IfcOpenShell
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ifcopenshell

      - name: Validate IFC files
        run: python3 path/to/your/script.py
