name: Validate IFC

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  validate-ifc:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install IfcOpenShell
      run: |
        python3 -m pip install --upgrade pip
        pip install ifcopenshell

    - name: Validate IFC file
      run: |
        python3 -c "
        import ifcopenshell
        ids = 'path/to/your/ids/file.ids'
        ifc = 'path/to/your/ifc/file.ifc'
        # Exemplo simples de validação
        try:
            model = ifcopenshell.open(ifc)
            project = model.by_type('IfcProject')
            if not project:
                raise ValueError('IfcProject ausente no arquivo IFC.')
            print('Arquivo IFC validado com sucesso!')
        except Exception as e:
            print(f'Erro na validação: {e}')
            exit(1)
        "
