name: Validate IFC

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  validate-ifc:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install IfcOpenShell
      run: |
        python3 -m pip install --upgrade pip
        pip install ifcopenshell

    - name: Validate all IFC files
      run: |
        import os
        import ifcopenshell

        # Diretório onde estão os arquivos
        repo_dir = os.getenv('GITHUB_WORKSPACE')

        # Listar todos os arquivos .ifc no repositório
        ifc_files = [
            os.path.join(repo_dir, f)
            for f in os.listdir(repo_dir)
            if f.endswith('.ifc')
        ]

        if not ifc_files:
            print("Nenhum arquivo IFC encontrado no repositório.")
            exit(1)

        # Caminho do arquivo IDS
        ids_path = os.path.join(repo_dir, "path/to/your/ids/file.ids")

        # Validação de cada arquivo IFC
        for ifc_file in ifc_files:
            print(f"Validando o arquivo: {ifc_file}")
            try:
                model = ifcopenshell.open(ifc_file)
                project = model.by_type('IfcProject')
                if not project:
                    raise ValueError(f"Erro: IfcProject ausente no arquivo {ifc_file}.")
                print(f"Arquivo {ifc_file} validado com sucesso!")
            except Exception as e:
                print(f"Erro na validação do arquivo {ifc_file}: {e}")
                exit(1)
