name: Validate IFC Files with IDS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-ifc:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ifcopenshell lxml

      - name: Validate IFC Files
        run: |
          python3 https://github.com/trevisan1234/validacao-ifc-ids

      - name: Upload Validation Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ifc-validation-report
          path: validation_report.json
